### ISSUE TITLE
Missing Outgoing and Incoming on Master Node accounts

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/nososova#55]
Hey Andrii(@pasichDev),

When you click on an account that is not being used as a Master Node, you can see the outgoing/incoming.

You've decided that to replace that, on the master nodes account, with the status of the Master Node and the income.

Can you add 2 more rounded rectangles below that so we can also have the incoming/outgoing, please?

Cheers,
Gus

**Comment by pasichDev** [comment]
In the future, I'll think about how to do it better and add it to the list of tasks.
