### ISSUE TITLE
On the Noso Price graph, the hint should have a date

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/nososova#56]
Hey Andrii(@pasichDev),

I'm very happy that you implemented the hint when we hover over the graph.

But I think the hint should include some reference of Date/Time.

Another suggestion would be to add a `1d | 1w | 1m | 1y | all` set of buttons, so we can have a finer grained view of the graph.

But hey, this is looking quite sharp !!!

Cheers,
Gus

**Comment by pasichDev** [comment]
move to https://github.com/Noso-Project/NosoSova/issues/4
