### ISSUE TITLE
Modifications to the Price Graph panel

### ISSUE THREAD

**Issue by gcarreno** [pasichDev/nososova#82]
Hey Andrii(@pasichDev),

- [ ] Put in separate thread
- [ ] On error, for the first connection, show message: Retrying in 10s.
- [ ] Have a "Retry now" button for above?
- [ ] Once data has been obtained, always keep that on.
- [ ] On error, having past data, just inform user via a small label, including a "Retry in 10s".

The amount of seconds is just a suggestion, you can decide on how many are a good amount.
If 2 errors in a row, maybe use the doubling thing, so you start with 10, then error, then you go to 20, then error, then you go to 40, etc...
Hope that makes sense !!

Cheers,
Gus

**Comment by pasichDev** [comment]
move to https://github.com/Noso-Project/NosoSova/issues/4
